var i: Int = 7;
var j: Int = 20;
var k: Int = i + j;
print(k, " = 7+20\n");
k = i-j;
print(k, " = 7-20\n");
k = i*j;
print(k, " = 7*20\n");
k = j/i;
print(k, " = 20/7\n");
k = j%i;
print(k, " = 20%%7\n");
k = -i;
print(k, " = -7\n");
k = i^3;
print(k, " 7^3\n");